Repository vmware/photon, pull requests merged in 2021-03, with the labels that each got.

#1129 Update working-with-kickstart.md
  content/en/docs-v3/user-guide/working-with-kickstart.md
Labels: documentation

#1139 Updating doc contribution
  CONTRIBUTING.md
  DOCS-CONTRIBUTING.md
  config.toml
  gh-pages.yml
  package-lock.json
  themes/photon-theme/CHANGES.md
  themes/photon-theme/assets/js/base.js
  themes/photon-theme/layouts/partials/page-meta-links.html
  themes/photon-theme/static/js/animated.js
Labels: cla-not-required, documentation

#1141 Update adding-a-new-repository.md
  content/en/docs-v3/administration-guide/managing-packages-with-tdnf/adding-a-new-repository.md
Labels: documentation

#1142 Update creating-a-startup-service.md
  content/en/docs-v3/administration-guide/managing-services-withsystemd/creating-a-startup-service.md
Labels: documentation

#1144 Update auditing-system-events-with-auditd.md
  content/en/docs-v3/administration-guide/managing-services-withsystemd/auditing-system-events-with-auditd.md
Labels: documentation

#1145 Update _index.md
  content/en/docs-v3/administration-guide/photon-rpm-ostree/host-updating-operations/_index.md
Labels: documentation

#1150 Update installing-photon-os-on-dell-500X.md
  content/en/docs-v3/installation-guide/install-photon-on-dell-gateway/installing-photon-os-on-dell-500X.md
Labels: documentation

#1152 Update prerequisites-for-photon-os-on-aws-ec2.md
  content/en/docs-v3/installation-guide/run-photon-aws-ec2/prerequisites-for-photon-os-on-aws-ec2.md
Labels: documentation

#1162 Update prerequisites-for-photon-os-on-gce.md
  content/en/docs-v3/installation-guide/run-photon-on-gce/prerequisites-for-photon-os-on-gce.md
Labels: documentation

#1165 cleanup package URLs
  content/en/docs/administration-guide/cloud-init-on-photon-os/customizing-a-photon-os-machine-on-ec2.md
  content/en/docs/administration-guide/cloud-init-on-photon-os/running-a-photon-os-machine-on-gce.md
  content/en/docs/administration-guide/managing-packages-with-tdnf/adding-a-new-repository.md
  content/en/docs/administration-guide/managing-packages-with-tdnf/adding-the-dev-repository.md
  content/en/docs/administration-guide/photon-os-packages/building-a-package-from-a-source-rpm.md
  content/en/docs/administration-guide/photon-os-packages/photon-os-package-repositories.md
  content/en/docs/administration-guide/photon-rpm-ostree/package-oriented-server-operations/_index.md
  content/en/docs/administration-guide/photon-rpm-ostree/remotes/_index.md
  content/en/docs/installation-guide/cloud-images.md
  content/en/docs/installation-guide/downloading-photon.md
  content/en/docs/installation-guide/run-photon-on-azure/prerequisites-for-photon-os-on-azure.md
  content/en/docs/installation-guide/run-photon-on-gce/prerequisites-for-photon-os-on-gce.md
  content/en/docs/installation-guide/run-photon-on-workstation/prerequisites-for-photon-os-on-workstation.md
  content/en/docs/installation-guide/upgrading-to-photon-os-4.md
  content/en/docs/troubleshooting-guide/troubleshooting-tools/common-tools.md
  content/en/docs/user-guide/kickstart-through-http/kickstart-procedure.md
  content/en/docs/user-guide/kickstart-through-http/packer-template.md
  content/en/docs/user-guide/setting-up-network-pxe-boot.md
  content/en/docs/user-guide/working-with-kickstart.md
Labels: cla-not-required

#1153 Update prerequisites-for-photon-os-on-azure.md
  content/en/docs-v3/installation-guide/run-photon-on-azure/prerequisites-for-photon-os-on-azure.md
Labels: documentation

#1154 Update setting-up-azure-storage-and-uploading-the-vhd.md
  content/en/docs-v3/installation-guide/run-photon-on-azure/setting-up-azure-storage-and-uploading-the-vhd.md
Labels: documentation

#1173 fixed link for photon graphic
  content/en/docs/_index.md
Labels: cla-not-required, documentation
