Repository vmware/photon, pull requests merged in 2021-06, with the labels that each got.

#1197 Package Version
  content/en/docs/command-line-reference/command-line-Interfaces/photon-management-daemon-cli.md
Labels: 4.0, documentation

#1195 Update configure-kubernetes-on-node.md
  content/en/docs/user-guide/kubernetes-on-photon-os/running-kubernetes-on-photon-os/configure-kubernetes-on-node.md
Labels: 4.0, documentation

#1198 Photon hugo
  content/en/docs/images/fsck-fails.png
  content/en/docs/images/lsblk-command.png
  content/en/docs/installation-guide/run-photon-on-raspberry-pi/installing-the-iso-image-for-photon-os-rpi.md
  content/en/docs/security-advisories/_index.md
  content/en/docs/troubleshooting-guide/file-system-troubleshooting/fixing-file-system-errors-when-fsck-fails.md
  content/en/docs/whats-new.md
Labels: cla-not-required, documentation

#1203 [Docs] Security Advisory updates + fixed syntax
  content/en/docs/security-advisories/_index.md
  content/en/docs/whats-new.md
Labels: cla-not-required

#1207 Syntax change in the What's New topic
  content/en/docs/whats-new.md
Labels: cla-not-required
