Repository vmware/photon, pull requests merged in 2022-01, with the labels that each got.

#1260 Update Packer Examples
  content/en/docs-v3/user-guide/kickstart-through-http/_index.md
  content/en/docs-v3/user-guide/kickstart-through-http/kickstart-prerequisites.md
  content/en/docs-v3/user-guide/kickstart-through-http/kickstart-procedure.md
  content/en/docs-v3/user-guide/kickstart-through-http/packages-minimal-json-file.md
  content/en/docs-v3/user-guide/kickstart-through-http/packer-template.md
  content/en/docs-v3/user-guide/packer-examples/_index.md
  content/en/docs/user-guide/kickstart-through-http/_index.md
  content/en/docs/user-guide/kickstart-through-http/kickstart-prerequisites.md
  content/en/docs/user-guide/kickstart-through-http/kickstart-procedure.md
  content/en/docs/user-guide/kickstart-through-http/packages-minimal-json-file.md
  content/en/docs/user-guide/kickstart-through-http/packer-template.md
  content/en/docs/user-guide/packer-examples/_index.md
  content/en/docs/user-guide/working-with-kickstart.md
Labels: documentation, cla-not-required

#1253 docs fixes (markdown, relative links, ..)
  content/en/docs-v3/administration-guide/managing-network-configuration/turning-on-network-debugging.md
  content/en/docs-v3/administration-guide/managing-packages-with-tdnf/adding-the-dev-repository.md
  content/en/docs-v3/administration-guide/managing-services-withsystemd/creating-a-startup-service.md
  content/en/docs-v3/administration-guide/photon-os-packages/building-a-package-from-a-source-rpm.md
  content/en/docs-v3/administration-guide/photon-rpm-ostree/install-or-rebase-to-photon-os-3/_index.md
  content/en/docs-v3/administration-guide/photon-rpm-ostree/package-oriented-server-operations/_index.md
  content/en/docs-v3/troubleshooting-guide/kernel-problems-and-boot-and-login-errors/boot-process-overview.md
  content/en/docs-v3/troubleshooting-guide/kernel-problems-and-boot-and-login-errors/investigating-unexpected-behavior.md
  content/en/docs-v3/troubleshooting-guide/kernel-problems-and-boot-and-login-errors/kernel-log-replication-with-vprobes.md
  content/en/docs-v3/troubleshooting-guide/solutions-to-common-problems/resetting-a-lost-root-password.md
  content/en/docs-v3/user-guide/working-with-kickstart.md
Labels: documentation

#1264 Update creating-a-stand-alone-photon-machine-with-cloud-init.md
  docs/photon_admin/creating-a-stand-alone-photon-machine-with-cloud-init.md
Labels: documentation

#1280 pmd-nextgen documentation
  content/en/docs/administration-guide/pmd-nextgen/Configuration.md
  content/en/docs/administration-guide/pmd-nextgen/How-to-write-your-plugin.md
  content/en/docs/administration-guide/pmd-nextgen/Installation.md
  content/en/docs/administration-guide/pmd-nextgen/_index.md
  content/en/docs/administration-guide/pmd-nextgen/feature.md
  content/en/docs/administration-guide/pmd-nextgen/photon-mgmtd-web-REST-API/_index.md
  content/en/docs/administration-guide/pmd-nextgen/photon-mgmtd-web-REST-API/network-management.md
  content/en/docs/administration-guide/pmd-nextgen/photon-mgmtd-web-REST-API/service-management.md
  content/en/docs/administration-guide/pmd-nextgen/photon-mgmtd-web-REST-API/system-management.md
  content/en/docs/administration-guide/pmd-nextgen/photon-mgmtd-web-REST-API/user-group-host-management.md
  content/en/docs/whats-new-photon-os-4-rev2-.md
Labels: cla-not-required

#1286 Modified a line in the Installation step
  content/en/docs/administration-guide/pmd-nextgen/Installation.md
Labels: cla-not-required
